sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t lemix777/backend-test -f ./backend/Dockerfile.dev ./backend

script:
  - docker run lemix777/backend-test npm run test
